config/routes.rb
Rails.application.routes.draw do
  root "home#show"

  get "dashboard", to: "users#show"

  get "feed", to: "feed#show"
  resources :pets, only: [:index, :show, :create]
  resources :tweets, only: [:new, :create]


  get "auth/twitter", as: :twitter_login
  get "auth/:provider/callback", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  has_many :pets_users
  has_many :users, through: :pets_users

  def self.find_or_create_from_auth(pet_info)
    pet = Pet.find_or_create_by(ad_url: pet_info['ad_url'])

    pet.name = pet_info['name']
    pet.image_url = pet_info['image_url']
    pet.description = pet_info['description']

    pet.save
    pet
  end
end

app/models/pets_user.rb
class PetsUser < ActiveRecord::Base
  belongs_to :pet
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pets_users
  has_many :pets, through: :pets_users

  def self.find_or_create_from_auth(auth)
    user = User.find_or_create_by(uid: auth['uid'], provider: auth['provider'])

    user.nickname = auth['info']['nickname']
    user.name = auth['info']['name']
    user.email = auth['info']['email']
    user.image_url = auth['info']['image']
    user.token = auth['credentials']['token']
    user.secret_token = auth['credentials']['secret']

    user.save
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize!
    redirect_to root_path unless current_user
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def index
    api_data = Faraday.get("http://pets.vsapi01.com/api-search/by-url?url=#{params["image"]}&apikey=5c3f0bd0-ab92-4fcc-9947-ad43dfcc99ac").body
    parsed_data = JSON.parse(api_data)
    @dogs = parsed_data["images"]
  end

  def show
  end

end

app/controllers/feed_controller.rb
class FeedController < ApplicationController

  def show
    @twitter = TwitterService.new(current_user)
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  def show
    @twitter = TwitterService.new(current_user)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    api_data = Faraday.get("http://pets.vsapi01.com/api-search/by-url?url=#{params["image"]}&apikey=#{ENV['JUST_VISUAL_KEY']}").body
    parsed_data = JSON.parse(api_data)
    @pets = parsed_data["images"]
    @new_pet = Pet.new
  end

  def show
  end

  def create
    @pet = Pet.find_or_create_from_auth(params)
    current_user.pets << @pet
    flash[:success] = "#{@pet.name} saved."
    redirect_to dashboard_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def new
    @tweet = "Your Tweet"
    @value = "Please help save this pet! #{params["ad"]}"
  end

  def create
    TwitterService.new(current_user).tweet(params["Your Tweet"]["content"])
    redirect_to dashboard_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authorize!, only: [:show]

  def show
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/index.html.erb
<h1>Here are your potential dream dogs!</h1>

<% @dogs.each do |dog| %>
  <%= link_to dog["pageUrl"] do %>
    <%= image_tag(dog["imageUrl"], class: "feed-pic") %>
  <% end %>
<% end %>

app/views/feed/show.html.erb
<div class="pics-wrapper">
  <h2>Which of these looks like your perfect pet?</h2>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-l2">
      <% @twitter.inspiration("doggy-inspiration").each do |tweet| %>
        <% if tweet.to_h[:entities] && tweet.to_h[:entities][:media] %>
          <% @pic_url = tweet.to_h[:entities][:media][0][:media_url_https] %>
          <div class="pic-container">
            <%= link_to pets_path(image: @pic_url), id: "pic-link" do %>
              <%= image_tag(@pic_url, class: "feed-pic hoverable") %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div> <!-- end of row -->
</div>

app/views/home/show.html.erb
<div class="home-wrapper valign-wrapper">
  <div class="home-content valign">
    <h1>PerfectPet</h1>
    <h3>Find the adoptable pet of your dreams.</h3>
    <%= link_to "Login with Twitter", twitter_login_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PerfectPet</title>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
  <%= stylesheet_link_tag    'css_reset', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <div class="nav-wrapper">
    <a href="#" class="brand-logo">PerfectPet</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to "Inspiration Feed", feed_path%></li>
      <li><%= link_to "Dashboard", dashboard_path %></li>
      <% if session[:user_id] %>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
      <% end %>
    </ul>
  </div>
</nav>

<% flash.each do |type, msg| %>
  <%= content_tag :span, sanitize(msg) %>
<% end %>

<%= yield %>

<!-- Compiled and minified JavaScript -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js">
 </script>
</body>
</html>

app/views/pets/index.html.erb
<div class="pics-wrapper">
  <h2>Here are your potential perfect pets!</h2>

  <div class="row">
    <div class="col s12 l10 offset-l1">
      <% if @pets.nil? %>
        <p>
          Sorry! We couldn't find a suitable match.
        </p>
      <% else %>
        <% @pets.each do |pet| %>
          <div class="pic-container">
            <div class="card">
              <div class="card-image">
                <%= image_tag(pet["imageUrl"], class: "feed-pic") %>
              </div>
              <div class="card-content">
                <span class="left-align truncate"><%= pet["petName"] %></span>
              </div>
              <div id="card-actions" class="card-action">
                <%= form_for @new_pet do |f| %>
                  <%= hidden_field_tag :name, pet["petName"] %>
                  <%= hidden_field_tag :image_url, pet["imageUrl"] %>
                  <%= hidden_field_tag :description, pet["description"] %>
                  <%= hidden_field_tag :ad_url, pet["pageUrl"] %>
                  <%= f.submit "Save", id: "submit-btn" %>
                <% end %>
                <!-- <%= link_to "Save", pets_path, method: :post %> -->
                <%= link_to "See Advertisement", pet["pageUrl"], class:"ad-link" %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div> <!-- end of row -->
</div>

app/views/tweets/new.html.erb
<h2 class="center">Spread the word!</h2>

<div class="container">
  <%= form_for(@tweet, url: tweets_path) do |f| %>
    <%= f.label :content %>
    <%= f.text_field :content, value: @value %>
    <%= f.submit "Post" %>
  <% end %>
</div>

app/views/users/_pets.html.erb
<% @user.pets.each do |pet| %>
  <div class="pic-container">
    <div class="card">
      <div class="card-image">
        <%= image_tag(pet.image_url, class: "feed-pic") %>
      </div>
      <div class="card-content">
        <span class="left-align truncate"><%= pet.name %></span>
      </div>
      <div id="card-actions" class="card-action">
        <%= link_to "See Advertisement", pet.ad_url, class:"ad-link" %>
        <%= link_to image_tag('/assets/twitter-logo.png', class: "twitter-logo"), new_tweet_path(ad: pet.ad_url) %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="dashboard-wrapper">
  <div class="dashboard-content valign-wrapper">
    <%= image_tag(@user.image_url, class: "circle") %>
    <h2 class="valign truncate"><%= @user.name %></h2>
  </div>
  <%= link_to "Find More Perfect Pets", feed_path, class: "find-more-btn" %>
  <div class="pets-wrapper container">
    <h3>Saved Pets</h3>
    <div class="saved-pets">
      <% if @user.pets.nil? %>
        <p>
          You have no saved pets!
        </p>
      <% else %>
        <%= render 'users/pets' %>
      <% end %>
    </div>
  </div>
</div>